import Head from 'next/head'

import useWindowSize from './hooks/useWindowSize'

import styles from '../styles/Home.module.css'

import SideOptions from './components/SideOptions'
import Game from './components/Game/Game'
import TopOptions from './components/AboveOptions'

export default function Home() {
  const wn = useWindowSize()

  return (
    <div className={styles.container}>
      <Head>
        <title>Snake app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Game wn={wn} canvasSize={wn.height - 50} />
        {
        //topOptions
        // - restart
        // - new game
        // - fullscreen
        // - pause
        }
        <SideOptions size={`${wn.width - (wn.height - 30)}px`} />
        <TopOptions />
      </main>
    </div>
  )
}
