import Head from 'next/head'

import useWindowSize from './hooks/useWindowSize'

import styles from '../styles/Home.module.css'

import BottomOptions from './components/BottomOptions'
import SideOptions from './components/SideOptions'
import TopOptions from './components/topOptions'
import Game from './components/Game/Game'

export default function Home() {
  const wn = useWindowSize()
  const canvasSize = wn.height - 250

  return (
    <div className={styles.container}>
      <Head>
        <title>Snake app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Game wn={wn} canvasSize={canvasSize} />
        {
        //topOptions
        // - restart
        // - new game
        // - fullscreen
        }
        <TopOptions />
        {
        //sideOptions
        // - bigger changes
        }
        <SideOptions size={`${wn.width - canvasSize}px`} />
        {
        //footerOptions
        // - smaller changes
        // - more apples
        // - change game colors
        }
        <BottomOptions />
      </main>
    </div>
  )
}
