import Head from 'next/head'

import useWindowSize from './hooks/useWindowSize'

import styles from '../styles/Home.module.css'

import SideOptions from './components/SideOptions'
import Game from './components/Game/Game'
import TopOptions from './components/AboveOptions'
import { useState } from 'react'

export default function Home() {
  const wn = useWindowSize()
  const [paused, setPaused] = useState(false)
  const [restart, setRestart] = useState(false)

  return (
    <div className={styles.container}>
      <Head>
        <title>Snake app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Game 
          wn={wn} 
          canvasSize={wn.height - 50} 
          paused={paused} 
          setPaused={setPaused} 
          restart={restart} 
          setRestart={setRestart} 
        />
        <SideOptions size={`${wn.width - (wn.height - 30)}px`} />
        <TopOptions 
          paused={paused}
          setPaused={setPaused} 
          restart={restart} 
          setRestart={setRestart}
        />
      </main>
    </div>
  )
}
